create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  display_name text not null check (char_length(trim(display_name)) between 1 and 24),
  subscriber_count integer not null default 50000 check (subscriber_count >= 0),
  last_subscriber_delta integer not null default 0,
  has_subscriber_outcome boolean not null default false,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists profiles_leaderboard_idx
  on public.profiles (subscriber_count desc, updated_at desc);

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at
before update on public.profiles
for each row
execute function public.set_updated_at();

alter table public.profiles enable row level security;

drop policy if exists "Authenticated users can view leaderboard" on public.profiles;
create policy "Authenticated users can view leaderboard"
on public.profiles
for select
to authenticated
using (true);

drop policy if exists "Users can insert their own profile" on public.profiles;
create policy "Users can insert their own profile"
on public.profiles
for insert
to authenticated
with check ((select auth.uid()) = id);

drop policy if exists "Users can update their own profile" on public.profiles;
create policy "Users can update their own profile"
on public.profiles
for update
to authenticated
using ((select auth.uid()) = id)
with check ((select auth.uid()) = id);

create table if not exists public.suggestions (
  id bigint generated by default as identity primary key,
  profile_id uuid not null references public.profiles(id) on delete cascade,
  email text not null,
  display_name text not null check (char_length(trim(display_name)) between 1 and 24),
  message text not null check (char_length(trim(message)) between 1 and 500),
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists suggestions_created_at_idx
  on public.suggestions (created_at desc);

alter table public.suggestions enable row level security;

drop policy if exists "Users can insert their own suggestions" on public.suggestions;
create policy "Users can insert their own suggestions"
on public.suggestions
for insert
to authenticated
with check ((select auth.uid()) = profile_id);

create table if not exists public.chat_messages (
  id bigint generated by default as identity primary key,
  room_id text not null check (room_id ~ '^[a-z0-9_-]{1,32}$'),
  profile_id uuid not null references public.profiles(id) on delete cascade,
  display_name text not null check (char_length(trim(display_name)) between 1 and 24),
  message text not null check (char_length(trim(message)) between 1 and 280),
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists chat_messages_room_id_id_idx
  on public.chat_messages (room_id, id desc);

create index if not exists chat_messages_profile_created_at_idx
  on public.chat_messages (profile_id, created_at desc);

alter table public.chat_messages enable row level security;

drop policy if exists "Authenticated users can view chat messages" on public.chat_messages;
create policy "Authenticated users can view chat messages"
on public.chat_messages
for select
to authenticated
using (true);

drop policy if exists "Users can insert their own chat messages" on public.chat_messages;
create policy "Users can insert their own chat messages"
on public.chat_messages
for insert
to authenticated
with check ((select auth.uid()) = profile_id);

create table if not exists public.projector_state (
  id text primary key check (id = 'main'),
  mode text not null default 'offline' check (mode in ('offline', 'live', 'replay', 'archive_pending')),
  live_video_id text not null default '',
  replay_video_id text not null default '',
  replay_clock_video_id text not null default '',
  replay_started_at timestamptz,
  replay_duration_seconds integer,
  pending_archive_video_id text not null default '',
  uploads_playlist_id text not null default '',
  check_lease_expires_at timestamptz,
  last_live_check_at timestamptz,
  last_archive_check_at timestamptz,
  last_source text not null default '',
  last_error text not null default '',
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

alter table public.projector_state
  add column if not exists replay_clock_video_id text not null default '';

alter table public.projector_state
  add column if not exists replay_started_at timestamptz;

alter table public.projector_state
  add column if not exists replay_duration_seconds integer;

insert into public.projector_state (id)
values ('main')
on conflict (id) do nothing;

drop trigger if exists projector_state_set_updated_at on public.projector_state;
create trigger projector_state_set_updated_at
before update on public.projector_state
for each row
execute function public.set_updated_at();

alter table public.projector_state enable row level security;

create or replace function public.claim_projector_refresh(lease_seconds integer default 20)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  rows_updated integer := 0;
begin
  insert into public.projector_state (id)
  values ('main')
  on conflict (id) do nothing;

  update public.projector_state
  set check_lease_expires_at = timezone('utc', now()) + make_interval(secs => greatest(lease_seconds, 5))
  where id = 'main'
    and (
      check_lease_expires_at is null
      or check_lease_expires_at < timezone('utc', now())
    );

  get diagnostics rows_updated = ROW_COUNT;
  return rows_updated > 0;
end;
$$;

revoke all on function public.claim_projector_refresh(integer) from public;
grant execute on function public.claim_projector_refresh(integer) to service_role;
